# fastlane/Fastfile
default_platform :ios

platform :ios do
  before_all do
    setup_circle_ci
    import_certificate(
      keychain_name: ENV["MATCH_KEYCHAIN_NAME"],
      keychain_password: ENV["MATCH_KEYCHAIN_PASSWORD"],
      certificate_path: 'Certificates.p12',
      certificate_password: ENV["CERTIFICATE_PASSWORD"] || "default"
    )
  end
  
  desc "Clean"
  lane :clean do
    clear_derived_data
  end

end